image: adoptopenjdk/openjdk11:slim

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  APP_JAR_PATH: "build/libs"
  APP_JAR_PREFIX: "batch"
  APP_REPORT_CODE_COVERAGE: "build/reports/jacoco/test/html/index.html"
  APP_REPORT_TEST: "build/test-results/test/TEST-*.xml"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew build jacocoTestReport
    - cat $APP_REPORT_CODE_COVERAGE
  artifacts:
    paths:
      - $APP_REPORT_CODE_COVERAGE
      - $APP_JAR_PATH/$APP_JAR_PREFIX-*.jar
    reports:
      junit: $APP_REPORT_TEST
    when: on_success
    expire_in: 30 days
    untracked: false
  except:
    - tags
