variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  APP_VERSION: 0.1.0

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle

stages:
  - test
  - build
  - package

test:
  stage: test
  image: openjdk:11-jre-slim
  script:
    - ./gradlew check
    - mv build/reports/jacoco/test/html/index.html index.html
    - cat index.html
  artifacts:
    paths:
      - index.html

build:
  stage: build
  image: openjdk:11-jre-slim
  script:
    - ./gradlew jar
    - mv build/libs/lucasvalente-0.1.0.jar ./
  artifacts:
    paths:
      - lucasvalente-0.1.0.jar
    when: on_success
    expire_in: 1 week
  only:
    - main

docker-image:
  stage: package
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build --tag gradle:4.10.1-jdk11-slim --file Dockerfile.gradleJdk11 .
    - docker build --tag "$CI_REGISTRY_IMAGE:$APP_VERSION" .
    - docker push "$CI_REGISTRY_IMAGE:$APP_VERSION"
  only:
    - main
